---

- name: install udev rule
  copy:
    content: |
      SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
      SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
    dest: /etc/udev/rules.d/backlight.rules
  notify: "reload udev rules"
  become: yes
