---

- name: install yubikey dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - yubico-piv-tool
      - yubikey-luks
      - yubikey-manager
      - yubikey-personalization
      - libpam-yubico
  become: yes

- name: install udev rules
  copy:
    src: 70-u2f.rules
    dest: /etc/udev/rules.d/70-u2f.rules
  notify: reload udev rules
  become: yes
