icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
#separator = ""
idle_bg = "#f1efee"
idle_fg = "#68615e"
info_bg = "#3d97b8"
info_fg = "#f1efee"
good_bg = "#7b9726"
good_fg = "#f1efee"
warning_bg = "#c38418"
warning_fg = "#f1efee"
critical_bg = "#f22c40"
critical_fg = "#f1efee"

[[block]]
block = "focused_window"
max_width = 20

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "net"
device = "wlan0"
interval = 5
ssid = false
ip = true
speed_up = false
speed_down = false

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"

[[block]]
block = "bluetooth"
mac = "34:88:5D:AB:38:8F"

[[block]]
block = "battery"
driver = "upower"
format = "{power}W/h {percentage}% {time}"

[[block]]
block = "keyboard_layout"
driver = "localebus"

[[block]]
block = "time"
interval = 60
format = "EU %R"
timezone = "Europe/Stockholm"

[[block]]
block = "time"
interval = 1
format = "LOC %d/%m %T"
