icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
#separator = ""
idle_bg = "#f1efee"
idle_fg = "#68615e"
info_bg = "#3d97b8"
info_fg = "#f1efee"
good_bg = "#7b9726"
good_fg = "#f1efee"
warning_bg = "#c38418"
warning_fg = "#f1efee"
critical_bg = "#f22c40"
critical_fg = "#f1efee"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "net"
device = "wlp2s0"
interval = 5
ssid = true
ip = true
speed_up = false
speed_down = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"

[[block]]
block = "battery"
interval = 5
upower = true
format = "{power}W/h {percentage}% {time}"


[[block]]
block = "time"
interval = 60
format = "EU %a %d/%m %R"
timezone = "Europe/Stockholm"

[[block]]
block = "time"
interval = 1
format = "LOC %F %T"
