#!/bin/sh

case $1 in
    pre) /usr/local/bin/powersave false ;;
    post)
    if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
    then
            /usr/local/bin/powersave true
    else
            /usr/local/bin/powersave false
    fi
    ;;
esac
exit 0
